spring:
  application:
    name: collector

  kafka:
    topic:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
    producer:
      properties:
        "bootstrap.servers": "localhost:9092"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.serializer.GeneralAvroSerializer

logging:
  level:
    ru.yandex.practicum: TRACE
    org.apache.kafka: ERROR