spring:
  application:
    name: collector

  kafka:
    producer:
      properties:
        "bootstrap.servers": "localhost:9092"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.serializer.GeneralAvroSerializer
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1


logging:
  level:
    ru.yandex.practicum: TRACE
    org.apache.kafka: ERROR